for i in {1..10}
do
    nvidia-docker run -e "THEANO_FLAGS=mode=FAST_RUN,device=gpu0,floatX=float32,allow_gc=True" -v /home/sehan2:/home/sehan2 amri228/theano_custom python /home/sehan2/Amia/task1/nn_model/train1.py --num_epochs 50 --num_models 1 --word_vectors '/home/sehan2/Amia/task1/nn_model/glove_embedding/word2vec_twitter_model.bin' --model_type cnn --train_data_X '/home/sehan2/Amia/task1/random4/task1_tweet'$i'.txt' --train_data_Y '/home/sehan2/Amia/task1/random4/task1_label'$i'.txt' --val_data_X '/home/sehan2/Amia/task1/random4/task1_dev_tweet'$i'.txt' --val_data_Y '/home/sehan2/Amia/task1/random4/task1_dev_label'$i'.txt' --checkpoint_dir '/home/sehan2/Amia/task1/nn_model/experiments/full/checkpoints' --checkpoint_name 'cnn_random4_'$i --seed $i
    #nvidia-docker run -e "THEANO_FLAGS=mode=FAST_RUN,device=gpu0,floatX=float32,allow_gc=True" -v /home/sehan2:/home/sehan2 amri228/theano_custom python /home/sehan2/Amia/task1/nn_model/train1.py --num_epochs 50 --num_models 1 --word_vectors '/home/sehan2/Amia/task1/nn_model/glove_embedding/word2vec_twitter_model.bin' --model_type cnn --train_data_X '/home/sehan2/Amia/task1/random2/task1_tweet'$i'.txt' --train_data_Y '/home/sehan2/Amia/task1/random2/task1_label'$i'.txt' --val_data_X '/home/sehan2/Amia/task1/random2/task1_dev_tweet'$i'.txt' --val_data_Y '/home/sehan2/Amia/task1/random2/task1_dev_label'$i'.txt' --checkpoint_dir '/home/sehan2/Amia/task1/nn_model/experiments/exp1/checkpoints' --checkpoint_name 'cnn_random2_'$i --seed $i
done

for i in {1..10}
do
    nvidia-docker run -e "THEANO_FLAGS=mode=FAST_RUN,device=gpu0,floatX=float32,allow_gc=True" -v /home/sehan2:/home/sehan2 amri228/theano_custom python /home/sehan2/Amia/task1/nn_model/train1.py --num_epochs 50 --num_models 1 --word_vectors '/home/sehan2/Amia/task1/nn_model/glove_embedding/word2vec_twitter_model.bin' --model_type cnn_att_word --train_data_X '/home/sehan2/Amia/task1/random4/task1_tweet'$i'.txt' --train_data_Y '/home/sehan2/Amia/task1/random4/task1_label'$i'.txt' --val_data_X '/home/sehan2/Amia/task1/random4/task1_dev_tweet'$i'.txt' --val_data_Y '/home/sehan2/Amia/task1/random4/task1_dev_label'$i'.txt' --checkpoint_dir '/home/sehan2/Amia/task1/nn_model/experiments/full/checkpoints' --checkpoint_name 'cnnattword_random4_'$i --seed $i
    #nvidia-docker run -e "THEANO_FLAGS=mode=FAST_RUN,device=gpu0,floatX=float32,allow_gc=True" -v /home/sehan2:/home/sehan2 amri228/theano_custom python /home/sehan2/Amia/task1/nn_model/train1.py --num_epochs 50 --num_models 1 --word_vectors '/home/sehan2/Amia/task1/nn_model/glove_embedding/word2vec_twitter_model.bin' --model_type cnn_att_word --train_data_X '/home/sehan2/Amia/task1/random2/task1_tweet'$i'.txt' --train_data_Y '/home/sehan2/Amia/task1/random2/task1_label'$i'.txt' --val_data_X '/home/sehan2/Amia/task1/random2/task1_dev_tweet'$i'.txt' --val_data_Y '/home/sehan2/Amia/task1/random2/task1_dev_label'$i'.txt' --checkpoint_dir '/home/sehan2/Amia/task1/nn_model/experiments/exp1/checkpoints' --checkpoint_name 'cnnattword_random2_'$i --seed $i
done

